<?xml version="1.0"?>
<package format="3">
  <name>bidirectional_motor_test</name>
  <version>0.2.0</version>
  <description>DJI RC gated sinusoidal DSHOT600 reversal test with optional ROS thrust timing.</description>
  <maintainer email="ssybh2@users.noreply.github.com">ssybh2</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>custom_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
